---
title: "Mapping bias and correlation following latidunal gradient"
output: html_document
date: "2025-08-08"
---

---

## Library

```{r, include=FALSE}

library(tidyverse)
library(rnaturalearth)
library(tidyr)
library(leaflet)
library(sf)
library(ggmap)
library(ggplot2)
library(plyr)
library(dplyr)
library(sf)
library(RColorBrewer)
library(ggpubr)
library(scales)

```

## SPLITTING SHAPEFILE ON LATITUDE

```{r, include=FALSE}

# LOADING DATA #

shp_moy <- st_read(file.path("carte","data","sdmean_mtmsi.shp")) 
shp_bias <- st_read(file.path("carte","data","bias_all.shp")) 
shp_bias_rel <- st_read(file.path("carte","data","bias_rel_all.shp")) 
shp_cor <- st_read(file.path("carte","data", "cor_all.shp")) 

min(shp_bias_rel$valeur, na.rm=TRUE)
max(shp_bias_rel$valeur, na.rm=TRUE)
min(shp_bias$valeur, na.rm=TRUE)
min(shp_bias$valeur, na.rm=TRUE)
min(shp_bias$valeur, na.rm=TRUE)

# bbox3 <- st_bbox(c(xmin = 3.36284, xmax = 31.16189, ymax = 48, ymin = 44.06151), crs = st_crs(4326))
# bbox2 <- st_bbox(c(xmin = 3.36284, xmax = 31.16189, ymax = 55, ymin = 48), crs = st_crs(4326))
# bbox1 <- st_bbox(c(xmin = 3.36284, xmax = 31.16189, ymax = 71.17592, ymin = 55), crs = st_crs(4326))
# 
#  # CORRELATION #
# sph_cor_list <- list()
# sph_cor_list[[1]] <- st_crop(shp_cor, bbox1)
# sph_cor_list[[2]] <- st_crop(shp_cor, bbox2)
# sph_cor_list[[3]] <- st_crop(shp_cor, bbox3)
# 
#  # BIAS #
# sph_bias_list <- list()
# sph_bias_list[[1]] <- st_crop(shp_bias, bbox1)
# sph_bias_list[[2]] <- st_crop(shp_bias, bbox2)
# sph_bias_list[[3]] <- st_crop(shp_bias, bbox3)
# 
#  # relative BIAS #
# sph_biasrel_list <- list()
# sph_biasrel_list[[1]] <- st_crop(shp_bias_rel, bbox1)
# sph_biasrel_list[[2]] <- st_crop(shp_bias_rel, bbox2)
# sph_biasrel_list[[3]] <- st_crop(shp_bias_rel, bbox3)

```

## MAPPING

```{r, include=FALSE}

  # country borders #
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')


                                      ###### MEAN MAX SD ######
  pMOY <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_moy, aes(fill = meanmax), colour=NA)+
  scale_fill_gradient2(low="white", high="royalblue3",
                       name="Snow depth maxima mean (m)", lim=c(0,2.2),#breaks=c(-0.8,-0.5,0,0.5,0.8),
                       guide = guide_colorbar(title.position="top", title.hjust=0.5, 
                                              barwidth = 10, barheight = 0.5))+
  coord_sf(xlim = c(0, 32), ylim = c(44, 71))+ 
  theme_light()+
  #labs(title = "(a)")+
  theme(axis.text = element_text(size=6), legend.title = element_text(size=10), legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"),
        plot.title = element_text(hjust = 0.5))

                                      ###### BIAS ######
#pBIAS <- list()

#for (lati in c(1:3)){
  
  pBIAS <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_bias, aes(fill = valeur), colour=NA)+
  scale_fill_gradient2(low="red", high="blue", mid="white", midpoint=0, 
                       name="Bias (m)", lim=c(-1.5,1.5),#breaks=c(-0.8,-0.5,0,0.5,0.8),
                       guide = guide_colorbar(title.position="top", title.hjust=0.5, 
                                              barwidth = 10, barheight = 0.5))+
  coord_sf(xlim = c(0, 32), ylim = c(44, 71))+ 
  theme_light()+
  #labs(title = "(a)")+
  theme(axis.text = element_text(size=6), legend.title = element_text(size=10), legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"),
        plot.title = element_text(hjust = 0.5))

#}



                                      ###### RELATIVE BIAS ######

#pBIASrel <- list()

#for (lati in c(1:3)){
  
  pBIASrel <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_bias_rel, aes(fill = valeur), colour=NA)+
  scale_fill_gradient2(low="red", high="blue", mid="white", midpoint=0, 
                       name="Bias (%)", lim=c(-230,230),#breaks=c(-0.8,-0.5,0,0.5,0.8),
                       guide = guide_colorbar(title.position="top", title.hjust=0.5, 
                                              barwidth = 10, barheight = 0.5))+
  coord_sf(xlim = c(0, 32), ylim = c(44, 71))+ 
  theme_light()+
  #labs(title = "(a)")+
  theme(axis.text = element_text(size=6), legend.title = element_text(size=10), legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"),
        plot.title = element_text(hjust = 0.5))

#}


                                      ###### CORRELATION ######
#pCOR <- list()

#for (lati in c(1:3)){
  
  pCOR <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_cor, aes(fill = valeur), colour=NA)+ #
  scale_fill_gradient2(low="white", high="darkgreen", mid="#ccece6", midpoint=0.5, 
                       lim=c(-0.1,1), name="Correlation", breaks=c(0,0.2,0.4,0.6,0.8,1),
                       guide = guide_colorbar(title.position="top", title.hjust=0.5, 
                                              barwidth = 10, barheight = 0.5))+ 
  coord_sf(xlim = c(0, 32), ylim = c(44, 71))+ 
  theme_light()+
  #labs(title = "(b)")+
  theme(axis.text = element_text(size=6), legend.title = element_text(size=10), legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"),
        plot.title = element_text(hjust = 0.5))
  
#}

  
# combi_biasrel <- ggarrange(pBIASrel[[1]], pBIASrel[[2]], pBIASrel[[3]], nrow=3, common.legend = TRUE, legend = 'bottom')
# combi_bias <- ggarrange(pBIAS[[1]], pBIAS[[2]], pBIAS[[3]], nrow=3, common.legend = TRUE, legend = 'bottom')
# combi_cor <- ggarrange(pCOR[[1]], pCOR[[2]], pCOR[[3]], nrow=3, common.legend = TRUE, legend = 'bottom')

png(file.path("carte","map_multi.jpg"), 
    width = 20, height = 30, units = "in", res=300)
ggarrange(pMOY, pBIASrel, pBIAS, pCOR, nrow = 2, ncol=2)
dev.off()


#####################



```

