---
title: 'Mapping data characteristics: stations and elevation evaluated'
output: html_document
date: "2025-08-27"
---

## Library

```{r, include=FALSE}

library(tidyverse)
library(rnaturalearth)
library(tidyr)
library(sf)
library(ggmap)
library(ggplot2)
library(plyr)
library(dplyr)
library(sf)
library(RColorBrewer)

```

## Amount of stations

```{r, include=FALSE}

# Loading shapefile
sf_stat <- st_read(file.path("obs", "nb_stat3857.shp"))

sf_stat_class <- sf_stat %>% mutate(class_stat = cut(nb_stat, breaks = c(0,10,50,100,150), labels=c("1-10","10-50","50-100","100-150")))

palette_stat = c("mistyrose", "plum2", "plum3", "plum4")

# Shapefile of country borders
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')

# Plot
pSTAT <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=sf_stat_class, aes(fill = class_stat), colour=NA)+
  scale_fill_manual(values=palette_stat)+ 
  guides(fill=guide_legend(title="Amount of stations", title.position = "top")) +
  coord_sf(xlim = c(-2, 32), 
              ylim = c(40, 71))+ 
  theme_light()+
  labs(title= "(a)")+
  theme(axis.text = element_text(size=6), 
        legend.position = "bottom", 
        legend.title = element_text(size=10, hjust=0.5),
        legend.text=element_text(size=9),
        plot.title = element_text(hjust = 0.5, size=10, face = "bold"))

```

## Amount of bands and station per band

```{r, include=FALSE}

# Loading shapefile
sf_nband <- st_read(file.path("carte", "data", "nb_bandNUT.shp"))
sf_nstatb <- st_read(file.path("carte", "data", "nb_stat_band.shp"))

sf_nband_class <- sf_nband %>% mutate(class_nband = cut(nb_band, breaks = c(0,1,10,20,25), labels=c("1","2-10","10-20","20-25")))
sf_nstatb_class <- sf_nstatb %>% mutate(class_nbstat = cut(nb_stat, breaks = c(0,5,10,20,30,65), labels=c("1-5","5-10","10-20","20-30","30-65")))



# Shapefile of country borders
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')

# Plot amount of bands

palette_band = c("#FFDEAD", "#FFC125", "#EE7600", "#8B4500")
pBAND <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=sf_nband_class, aes(fill = class_nband), colour=NA)+
  scale_fill_manual(values=palette_band)+ 
  guides(fill=guide_legend(title="Amount of MTMSI elevation bands", title.position = "top")) +
  coord_sf(xlim = c(-2, 32), 
              ylim = c(40, 71))+ 
  labs(title = "(b)")+
  theme_light()+
  theme(axis.text = element_text(size=6), 
        legend.position = "bottom", 
        legend.title = element_text(size=10, hjust=0.5),
        legend.text=element_text(size=9),
        plot.title = element_text(hjust = 0.5, size=10, face = "bold"))


# Plot amount of station per band

palette_nstat = c("#BAC8F0","#A0BFE6", "#6CABD3", "#3798BF","#0384AB")
pSTATBAND <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=sf_nstatb_class, aes(fill = class_nbstat), colour=NA)+
  scale_fill_manual(values=palette_nstat)+ 
  guides(fill=guide_legend(title="Amount of stations per elevation band", title.position = "top")) +
  coord_sf(xlim = c(-2, 32), 
              ylim = c(40, 71))+ 
  labs(title = "(c)")+
  theme_light()+
  theme(axis.text = element_text(size=6), 
        legend.position = "bottom", 
        legend.title = element_text(size=10, hjust=0.5),
        legend.text=element_text(size=9),
        plot.title = element_text(hjust = 0.5, size=10, face = "bold"))

###
# Faire pEVAL dans code 'score_histogram'
###


png(file.path("carte","NB_stat2.jpg"), 
    width = 8, height = 8, units = "in", res=300) #20 25
ggarrange(pSTAT, pBAND, pSTATBAND, pEVAL, nrow = 2, ncol=2)
dev.off()


```