---
title: "Mapping evaluation scores"
output: html_document
date: "2024-07-19"
---
We map side by side the correlation and bias on each NUTS-3 mean elevation that have been assessed
In a similar way we map in another single file the KGE scores
---
## Library

```{r, include=FALSE}

library(tidyverse)
library(rnaturalearth)
library(tidyr)
library(leaflet)
library(sf)
library(ggmap)
library(ggplot2)
library(plyr)
library(dplyr)
library(sf)
library(RColorBrewer)
#library(Polychrome)
library(ggpubr)
library(scales)
library(ggnewscale)

```

## BIAS

```{r, include=FALSE}

shp_bias <- st_read(file.path("carte","data","bias_all.shp")) 
  # country borders #
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')

pBIAS <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_bias, aes(fill = valeur), colour=NA)+
  scale_fill_gradient2(low="red", high="blue", mid="white", midpoint=0, 
                       name="Bias (m)", lim=c(-1.5,1.5),#breaks=c(-0.8,-0.5,0,0.5,0.8),
                       guide = guide_colorbar(title.position="top", title.hjust=0.5, 
                                              barwidth = 10, barheight = 0.5))+
  coord_sf(xlim = c(0, 32), ylim = c(42, 71))+ 
  theme_light()+
  labs(title = "(a)")+
  theme(axis.text = element_text(size=6), legend.title = element_text(size=10), legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"),
        plot.title = element_text(hjust = 0.5))

png(file.path("carte","mapBIAS.jpg"), 
    width = 10, height = 8, units = "in", res=300)
pBIAS
dev.off()


```

## CORRELATION

```{r, include=FALSE}

shp_cor <- st_read(file.path("carte","data", "cor_all.shp")) 

pCOR <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_cor, aes(fill = valeur), colour=NA)+ #
  scale_fill_gradient2(low="white", high="darkgreen", mid="#ccece6", midpoint=0.5, 
                       lim=c(-0.1,1), name="Correlation", breaks=c(0,0.2,0.4,0.6,0.8,1),
                       guide = guide_colorbar(title.position="top", title.hjust=0.5, 
                                              barwidth = 10, barheight = 0.5))+ 
  coord_sf(xlim = c(0, 32), ylim = c(42, 71))+ 
  theme_light()+
  labs(title = "(b)")+
  theme(axis.text = element_text(size=6), legend.title = element_text(size=10), legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"),
        plot.title = element_text(hjust = 0.5))

png(file.path("carte","mapCOR.jpg"), 
    width = 10, height = 8, units = "in", res=300)
pCOR
dev.off()

```

## KGE

```{r, include=FALSE}
# LOADING DATA #

shp_kge <- st_read(file.path("carte","data","kge_all.shp")) 
shp_kge3857 <- st_transform(shp_kge, 3857)
  # country borders #
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')

shp_kge_class <- shp_kge %>% mutate(class_kge = cut(valeur, breaks = c(-3,-2,-1,-0.41,0,0.5,1), labels=c("-3;-2","-2;-1","-1;-0.41","-0.41;0","0;0.5","0.5,1")))
palette_kge <- c("firebrick1","chocolate1","khaki1", "darkseagreen1","steelblue1", "darkblue")

# pKGE <- ggplot() +
#   geom_sf(data=worldmap)+
#   geom_sf(data=shp_kge, aes(fill = valeur), colour=NA)+
#   scale_fill_gradientn(colors=c("firebrick1","chocolate1","khaki1", "darkseagreen1","steelblue1", "darkblue"), values = rescale(c(-3,-2,-1,-0.41,0,0.5,1)), name="KGE", limits=c(-3,1), breaks=c(-3,-1.5,-0.41,1), 
#                        guide = guide_colorbar(title.position="top", title.hjust=0.5,
#                                               barwidth = 10, barheight = 0.5))+
#   coord_sf(xlim = c(0, 32), ylim = c(42, 71))+ 
#   theme_light()+
#   theme(axis.text = element_text(size=6), legend.title = element_text(size=10), 
#         legend.position = "bottom",
#         panel.background = element_rect(fill = "lightsteelblue2"))

pKGE <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_kge_class, aes(fill = class_kge), colour=NA)+
  scale_fill_manual(values=palette_kge)+ 
  guides(fill=guide_legend(title="KGE", title.position = "top", nrow=1)) +
  coord_sf(xlim = c(0, 32), ylim = c(42, 71))+ 
  theme_light()+
  theme(axis.text = element_text(size=6), 
        legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"),
        legend.title = element_text(size=10, hjust=0.5))


png(file.path("carte","mapKGE.jpg"), 
    width = 10, height = 8, units = "in", res=300)
pKGE
dev.off()



```

## KGE GAMMA

```{r, include=FALSE}

shp_gamma <- st_read(file.path("carte","data","kge_gamma_all.shp")) 
  
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')

shp_gamma_class <- shp_gamma %>% mutate(class_gamma = cut(valeur, breaks = c(0.5,0.8,1.2,1.5,1.7,2), labels=c("0.5;0.8","0.8;1.2","1.2;1.5","1.5;1.7","1.7;2")))
palette_gamma <- c("#D4A8E6", "#47CD41","khaki1", "chocolate1", "#9A4A00")

pGAMMA <- ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_gamma_class, aes(fill = class_gamma), colour=NA)+
  scale_fill_manual(values=palette_gamma)+ 
  guides(fill=guide_legend(title="Gamma", title.position = "top")) +
  coord_sf(xlim = c(0, 32), ylim = c(42, 71))+ 
  theme_light()+
  theme(axis.text = element_text(size=6), 
        legend.title = element_text(size=10, hjust=0.5), 
        legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"))

png(file.path("carte","mapKGE.jpg"), 
    width = 10, height = 10, units = "in", res=300)
pGAMMA
dev.off()

#####################################################
# KGE and GAMMA side by side
#####################################################

png(file.path("carte","mapKGE_GAMMA.jpg"), 
    width = 10, height = 8, units = "in", res=300)
ggarrange(pKGE,pGAMMA,ncol=2, legend = "bottom")
dev.off()


```

## MAE

```{r, include=FALSE}

shp_mae <- st_read(file.path("carte","data","mae_all.shp")) 
  
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')

shp_mae$valeur[which(shp_mae$valeur>=1.6)]<-"above_2.5"



png(file.path("carte","map_mae.jpg"), 
    width = 10, height = 8, units = "in", res=300)

ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_mae %>% filter(valeur!="above_2.5"), aes(fill = as.numeric(valeur)), colour=NA)+
  scale_fill_gradientn(colors=c("#195F24", "#9FE67B", "yellow", "#EC8B3D"), #
                       values = rescale(c(0,0.4,0.8,1.2,1.6)), name="MAE (m)", limits=c(0,1.6), 
                       breaks=c(0,0.4,0.8,1.2,1.6), 
                       guide = guide_colorbar(title.position="top", title.hjust=0.5,
                                              barwidth = 10, barheight = 0.5))+
  new_scale_fill() +
  geom_sf(data=shp_mae %>% filter(valeur=="above_2.5"), aes(fill = as.factor(valeur)), colour=NA)+
  scale_fill_manual(name='MAE > 2.5m',values=c(above_2.5="#750C9F"), labels = NULL)+
  coord_sf(xlim = c(0, 32), ylim = c(42, 71))+ 
  theme_light()+
  theme(axis.text = element_text(size=6), legend.title = element_text(size=10), 
        legend.position = "bottom",
        panel.background = element_rect(fill = "lightsteelblue2"))

dev.off()

```

## OPTIONNAL --- Mapping scores on a selected elevation
It requires to have computed the required shapefile beforehand!

```{r, include=FALSE}

sel.alt = 2500

    # country borders #
worldmap <- ne_countries(scale = 'medium', type = 'map_units',
                         returnclass = 'sf')
worldmap3857 <- st_transform(worldmap, 3857) # we convert crs to pseudo mercator


                                      ###### MAPPING BIAS ######

shp_altbias <- st_read(file.path("carte", "data", paste0("bias",elevation,".shp"))) 
bounbox = st_bbox(shp_altbias)

png(file.path("carte", paste0("bias",elevation,"_map.png")), 
    width = 10.06, height = 5, units = "in", res=300)

ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_altbias, aes(fill = score), colour="black")+
  scale_fill_gradient2(low="blue", high="red", mid="white", midpoint=0, n.breaks=8, name="Bias")+
  coord_sf(xlim = c(bounbox[1],bounbox[3]), 
              ylim = c(bounbox[2],bounbox[4]))+ 
  theme_light()+
  theme(axis.text = element_text(size=6))

dev.off()

                                      ###### MAPPING CORRELATION ######

shp_altcor <- st_read(file.path("carte", "data", paste0("cor",elevation,".shp"))) 
bounbox = st_bbox(shp_altcor)

png(file.path("carte",paste0("cor",elevation,"_map.png")), 
    width = 10.06, height = 5, units = "in", res=300)

ggplot() +
  geom_sf(data=worldmap)+
  geom_sf(data=shp_altcor, aes(fill = score), colour="black")+
  scale_fill_gradient2(low="white", high="#006d2c", mid="#ccece6", midpoint=0.5, n.breaks=8, name="Correlation")+
  coord_sf(xlim = c(bounbox[1],bounbox[3]), 
              ylim = c(bounbox[2],bounbox[4]))+ 
  theme_light()+
  theme(axis.text = element_text(size=6))

dev.off()


#################################



```

