---
title: "Shapefile of number of in-situ stations per NUTS"
output: html_document
date: "2025-01-24"
---
We compute the shapefile of all the available stations (i.e. with at least one measure) per NUTS-3, no matter there altitude.
---

## Library

```{r, include=FALSE}

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(ncdf4)
library(sf)
library(readODS)

```

## Loading files

```{r, include=FALSE}

obs_sf <- st_read(file.path("obs", "obs_sf_nut.shp"))
obs_max <- get(load(file = file.path("obs","obs_max.RData")))
hist_nut <- st_read(file.path("mtmsi_hist", "max-sd-NS-year_sf_nut.shp")) 
nuts_hist <- unique(hist_nut$nuts_id)

# NUTS3
shp_nut3 <- st_read(file.path("NUTS","NUTS3_3857.shp"))

# SCORE
score_list <- get(load(file.path("mtmsi_hist", "score", "intcormin_list.RData"))) 
altitude_list <- get(load(file.path("mtmsi_hist","score", "alt_list.RData"))) # valeur d'altitudes par nuts
stat_list <- get(load(file.path("mtmsi_hist","score", "stat_list.RData"))) # nb stations par altitude par nuts (nested list)

```

## Computing shapefile of NUMBER OF STATIONS per NUTS
We filter out stations with no data at all.

```{r, include=FALSE}

obs_max2 <- obs_max
obs_max2$nyear <- apply(obs_max, 1, function(x) length(which(!is.na(x))))
row_statok <- which(obs_max2$nyear>=1) # get row indice where stations have at least one measure
id_statok <- obs_sf$stat_id[row_statok]

obs_sf_filt <- obs_sf[row_statok,]

sf_nstatemp = as.data.frame(obs_sf_filt %>% group_by(nuts_id) %>% dplyr::summarise(nb_stat=n())) %>% select(nuts_id,nb_stat)

sf_nstat = merge(shp_nut3, sf_nstatemp, by='nuts_id')

st_write(sf_nstat, file.path("obs", "nb_stat3857.shp"), delete_layer = TRUE)
  
```

## Computing shapefile of NUMBER OF EVALUATED BANDS/ MEAN AMOUNT OF STAT PER BAND per NUTS

```{r, include=FALSE}

df_evalband <- data.frame()

for (i in c(1:length(nuts_hist))){

  scor=score_list[[i]]
  alt=altitude_list[[i]]
  stat=stat_list[[i]]
  df_temp=data.frame(valeur=scor, altitude=alt, station=stat, nuts_id=nuts_hist[i])

  df_evalband=rbind(df_evalband,df_temp)
}

df_evalband = df_evalband %>% na.omit()

## Amount of evaluated altitude bands
nb_band = df_evalband %>% group_by(nuts_id) %>% dplyr::summarise(nb_band=n())
sf_nbband = merge(shp_nut3, nb_band, by='nuts_id')

## Mean amount of station per evaluated altitude band
nb_stat = df_evalband %>% group_by(nuts_id) %>% dplyr::summarise(nb_stat=mean(station))
sf_nbstat = merge(shp_nut3, nb_band, by='nuts_id')

st_write(sf_nbband, file.path("carte", "data", "nb_bandNUT.shp"), delete_layer = TRUE)
st_write(sf_nbstat, file.path("carte", "data", "nb_stat_band.shp"), delete_layer = TRUE)

```
